Fix typos
crossbario/autobahn-python pull request #1650
Opened 2024-10-27 16:05 UTC by kianmeng

Found via `codespell -L datas,ser,readd,wont,frameword` and `typos --hidden --format brief`

2024-10-27 22:31 UTC, oberstet commented
approved (only needed once), to run the CI ... however, unfortunately, the PR "fixes typos" not only in comments and docstrings, but also in member variable names and similar (identifier) : could you remove any changes to identifiers, only keeping comment/docstring changes?

2024-10-28 17:18 UTC, kianmeng commented
@oberstet Done.

2024-10-28 17:28 UTC, om26er commented
would probably make sense to integrate codepspell in CI as well

2024-10-28 19:02 UTC, oberstet requested changes
only 1 change left .. pls see below ... if you disagree, pls say so, np, let's discuss - I am _not_ a native speaker ..

2024-10-28 19:03 UTC, oberstet commented on autobahn/util.py
>      :param lower_case: If ``True``, generate token in lower-case.
as in (I think, but I'm non-native): **separator is the single character used to split the input string into resulting individual separated string (portions / parts / components)**

2024-10-28 19:43 UTC, oberstet commented
> would probably make sense to integrate codepspell in CI as well

oh yes, "some" spellchecker, preferably one in wide use within Sphinx / Python packages

in general, I kinda regret not having setup docs with all bells and whistles, and CI test-enforce stuff like correct spelling then

_if_ we had done that from day 1, the hurdle to pull that off now is much bigger

fwiw, in a new project I am working on, I did that (and more CI etc) from day 1 .. TDD .. or TDCI .. e.g. deciding to add and maintain a glossary has paid of hugely (for myself), also the other reference sections which of course are just "best practice" in advanced projects

![grafik](https://github.com/user-attachments/assets/e051f57a-e424-4bdf-82c0-8587abda1c10)

2024-10-28 20:05 UTC, meejah commented on autobahn/util.py
>      :param lower_case: If ``True``, generate token in lower-case.
Yes, "separator" is correct

2024-10-28 20:14 UTC, oberstet commented on autobahn/util.py
>      :param lower_case: If ``True``, generate token in lower-case.
while nitpicking, and looking at the type hints we have

https://github.com/crossbario/autobahn-python/blob/7bc85b34e200640ab98a41cfddb38267f39bc92e/autobahn/util.py#L370

is that even "correct"?

I mean `sep: Optional[str] = None,` allows both strings of length 1, and strings of other lengths, while actually it must be 1 char (if non None) ..

2024-10-28 20:17 UTC, oberstet commented on autobahn/util.py
>      :param lower_case: If ``True``, generate token in lower-case.
mmh, yeah, I know that, but that's not a type declaration, but a run-time type check ...

![grafik](https://github.com/user-attachments/assets/00a2a53d-d223-4ac1-8e90-bc87f1b945e1)

2024-10-28 20:25 UTC, meejah commented on autobahn/util.py
>      :param lower_case: If ``True``, generate token in lower-case.
AFAIK the bolted on Python type system is not robust enough to handle "N-character string" in the type-hinting (only, as per above, via runtime checks).

2024-10-28 20:26 UTC, oberstet commented on autobahn/util.py
>      :param lower_case: If ``True``, generate token in lower-case.
seems to be unavailable, at least today (well, and if the AI doesn't lie/hallucinate;)

![grafik](https://github.com/user-attachments/assets/6ccaa25e-6d80-4a7f-b769-443702fa9038)

2024-10-28 20:37 UTC, oberstet commented on autobahn/util.py
>      :param lower_case: If ``True``, generate token in lower-case.
```rust
struct SingleChar(String);

impl SingleChar {
    pub fn new(value: &str) -> Option<Self> {
        if value.chars().count() == 1 {
            Some(SingleChar(value.to_string()))
        } else {
            None // Returns None if the input is not exactly one character
        }
    }
}

fn check_single_char(input: Option<SingleChar>) {
    // No runtime check is necessary; input is already guaranteed to be either
    // a valid `SingleChar` or `None`.
}
```

2024-10-28 22:27 UTC, meejah commented on autobahn/util.py
>      :param lower_case: If ``True``, generate token in lower-case.
I think Haskell would just be:

```
import Data.Char

my_fn :: Char -> Nothing
```

2024-10-29 01:00 UTC, oberstet commented on autobahn/util.py
>      :param lower_case: If ``True``, generate token in lower-case.
yeah, definitely very nice example.

truth is, _only_ looking at the type system, Haskell (and formerly ML) are unmatched in their underpinnings as they are based on *typed lambda calculus* (https://en.wikipedia.org/wiki/Typed_lambda_calculus)

now, the fact that Haskell not only has a solid type foundation, but also nice terse algebraic surface syntax makes it even more interesting.

on the other hand, if you'd ask me for the "best syntax" ... obviously taste comes into play .. and so on, but there is one specific argument I always was attracted to:

LISP does away with any surface syntax, and it has this powerful macro thing, which sits on top of https://en.wikipedia.org/wiki/Homoiconicity as an afterburner.

well, and then there is the real world. countless pretty good Python packages;) get stuff done. batteries included.

anyways, nice comment - kudos @meejah

2024-10-29 19:15 UTC, oberstet commented
rgd

https://github.com/crossbario/autobahn-python/actions/runs/11577829463/job/32239966210?pr=1650

it seems this - no longer - works

https://github.com/crossbario/autobahn-python/blame/master/docs/conf.py#L334

----


rgd 

https://github.com/crossbario/autobahn-python/actions/runs/11577829463/job/32239969168?pr=1650#step:6:513

```
        Makefile.am: installing 'build-aux/depcomp'
        parallel-tests: installing 'build-aux/test-driver'
        configure: error: No modern nasm or yasm found as required. Nasm should be v2.11.01 or later (v2.13 for AVX512) and yasm should be 1.2.0 or later.
        thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/isal-sys-0.5.3+496255c/build.rs:72:17:
        configure failed
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
      warning: build failed, waiting for other jobs to finish...
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_ENVIRONMENT_SIGNATURE="pypy-3.9-64bit" PYO3_PYTHON="/opt/hostedtoolcache/PyPy/3.9.19/x64/bin/python" PYTHON_SYS_EXECUTABLE="/opt/hostedtoolcache/PyPy/3.9.19/x64/bin/python" "cargo" "rustc" "--message-format" "json-render-diagnostics" "--manifest-path" "/tmp/pip-install-uuwys2qy/cramjam_a007390a70fa43a58e37a6ed8923bea7/Cargo.toml" "--release" "--lib" "--" "-C" "strip=symbols"`
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/opt/hostedtoolcache/PyPy/3.9.19/x64/bin/python', '--compatibility', 'off'] returned non-zero exit status 1
      [end of output]
```

**configure: error: No modern nasm or yasm found as required. Nasm should be v2.11.01 or later (v2.13 for AVX512) and yasm should be 1.2.0 or later.**

wtf. why?

2024-10-29 19:17 UTC, oberstet requested changes
I'm sorry, it seems hard to get 100% green CI, and I'm pretty sure the remaining issue (pls see my comment) are unrelated, but ...

2025-01-19 07:54 UTC, closed without merging